# combination action page number and mp3 file path
action_and_sound: 
  1 : "/media/SOFTWARE/OP3/src/ROBOTIS-OP3-Demo/op3_demo/data/mp3/Intro01.mp3"
  2 : "/media/SOFTWARE/OP3/src/ROBOTIS-OP3-Demo/op3_demo/data/mp3/Intro02.mp3"
  3 : "/media/SOFTWARE/OP3/src/ROBOTIS-OP3-Demo/op3_demo/data/mp3/Intro03.mp3"