id_joint:
  1  : r_sho_pitch
  2  : l_sho_pitch
  3  : r_sho_roll
  4  : l_sho_roll
  5  : r_sho_yaw
  6  : l_sho_yaw
  7  : r_el
  8  : l_el
  11  : r_hip_yaw
  12  : l_hip_yaw
  9  : r_hip_roll
  10 : l_hip_roll
  13 : r_hip_pitch
  14 : l_hip_pitch
  15 : r_knee
  16 : l_knee
  17 : r_ank_pitch
  18 : l_ank_pitch
  26 : head_pan 
  27 : head_tilt
  21 : abs_y
  22 : abs_x
  23 : abs_z
  24 : bust_y
  25 : bust_x
  200 : opencr
module_list: [none, head_control_module, base_module, walking_module, manipulation_module, action_module, walking_module, direct_control_module, online_walking_module]
module_button:
  1 : none
  2 : head_control_module
  3 : action_module
  4 : walking_module
  5 : online_walking_module
  6 : direct_control_module
