# time parameter

mov_time : 3.0		# movement time

# target pose [deg]

tar_pose :
  l_ank_pitch:    0.0
  l_ank_roll:     0.0
  l_el:           0.0
  l_hip_pitch:    0.0
  l_hip_roll:     0.0
  l_hip_yaw:      0.0
  l_knee:         0.0
  l_sho_pitch:    0.0
  l_sho_roll:     0.0
  l_sho_yaw:      0.0
  r_ank_pitch:    0.0
  r_ank_roll:     0.0
  r_el:           0.0
  r_hip_pitch:    0.0
  r_hip_roll:     0.0
  r_hip_yaw:      0.0
  r_knee:         0.0
  r_sho_pitch:    0.0
  r_sho_roll:     0.0
  r_sho_yaw:      0.0
  abs_y:          0.0
  abs_x:          0.0
  abs_z:          0.0
  bust_y:         0.0
  bust_x:         0.0
